common:
    method: ours

    net:
        type: Transporter_v2
        kwargs:
            c_dim: 32
            input_type: pointcloud
            sigmoid: True

            encoder: pointnet_local_pool
            encoder_kwargs:
                hidden_dim: 32
                plane_type: 'grid'
                grid_resolution: [64, 64, 64]
                unet3d: True
                unet3d_kwargs:
                    num_levels: 4
                    f_maps: 32
                    in_channels: 32
                    out_channels: 32
            
            keypointnet:
                encoder: pointnet_atten_cross
                encoder_kwargs:
                    attn_kwargs:
                        type: simple
                    hidden_dim: 32
                    plane_type: 'grid'
                    grid_resolution: [64, 64, 64]
                    unet3d: True
                    unet3d_kwargs:
                        num_levels: 4
                        f_maps: 32
                        in_channels: 32
                        out_channels: 6
                decoder_kwargs:
                    std: 0.2
            
            decoder:
                decoder_occup: 
                    decoder_type: simple_local
                    decoder_kwargs:
                        sample_mode: bilinear # bilinear / nearest
                        hidden_size: 32
    
    solver:
        type: Solver
    
    public_params:
        input_pcd_num: 5000
        on_occupancy_num: 2000 # 1000
        off_occupancy_num: 500 # 1000
        padding: 0
        z_min: -0.5
        z_max: 0.5

    workers: 4
    batch_size: 1
    deterministic: True
    random_seed: 123


augmentation:
    do_aug: False
    rotate_angle: 360
    rotate_dim: 3D
    sigma: 0.0
    clip: 0.0
    dif_length: 10


data_info:
    dataset_name: bullet
    data_path: data/bullet_multi_joint_test
    test_type: seen
    # test_cat_name: ['Refrigerator', 'FoldingChair', 'Laptop', 'Stapler', 'TrashCan', 'Microwave', 'Toilet', 'Window', 'StorageFurniture', 'Kettle']
    test_cat_name: ['Door']
    model_path: checkpoints/model_best.pth


test:
    grid_sample: True
    grid_kwargs:
        x_res: 100
        y_res: 100
        z_res: 100
    
    noise_std: 0
    downsample: 1

    occupancy_thr: 0.8
    
    loss:
